function [dx] = auto_odes(SIMINT_TIME,x,S)
% % DO NOT EDITED THIS FILE
% %
% % This function was automatically generated by 
% % build_system.pl       
% %
% % It is called internally by run_simulation_generic.m
% pulling out the inputs at the current simulation time
u = interp1(S.blocks.all_inputs(:,1), S.blocks.all_inputs, SIMINT_TIME);
% The first column is the interpolated time,
% so we remove that one.
u = u(1,2:end);
% Defining parameters 
PNAME       = u(1); 



%  Mapping states to their common names 
TMP          = x(1);
SIMINT_dTMP   = (0.0);


%remapping the ODEs back to dx
dx(1,1) = SIMINT_dTMP; 
