function [som]=auto_map_simulation_output(so,cfg) 
% function [som]=auto_map_simulation_output(so,cfg) 
% % DO NOT EDITED THIS FILE
% %
% % This function was automatically generated by 
% % build_system.pl       
% %
% % It takes one argume (so), the output from run_simulation_generic and returns the data
% % structure 'som' with named fields for times, states, and outputs.

m = cfg.options.mi;

% the raw simulation output 
som.raw      = so;
som.times.sim_time = so.t; 
 


% Mapping state output
som.states.TMP          = so.x(:,m.states.TMP); 



% Mapping output output
som.outputs.TMP_OBS       = so.y(:,m.outputs.TMP_OBS); 



% Mapping time scales
som.times.sys_time     = so.t*1.0; 
